// <auto-generated />
using System;
using Carrel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrel.Api.Data.Migrations
{
    [DbContext(typeof(CarrelDbContext))]
    [Migration("20261005224249_AddLibraryImports")]
    partial class AddLibraryImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrel.Api.Data.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("HardcoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("hardcover_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OpenLibraryAuthorKey")
                        .HasColumnType("text")
                        .HasColumnName("open_library_author_key");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("HardcoverId")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_hardcover_id");

                    b.HasIndex("OpenLibraryAuthorKey")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_open_library_author_key");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CoverSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("cover_suppressed");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionSource")
                        .HasColumnType("text")
                        .HasColumnName("description_source");

                    b.Property<bool>("DescriptionSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("description_suppressed");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FirstPublishedYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_published_year");

                    b.Property<long?>("HardcoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("hardcover_id");

                    b.Property<decimal?>("HardcoverRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("hardcover_rating");

                    b.Property<int?>("HardcoverRatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("hardcover_ratings_count");

                    b.Property<string>("OpenLibraryWorkKey")
                        .HasColumnType("text")
                        .HasColumnName("open_library_work_key");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("HardcoverId")
                        .IsUnique()
                        .HasDatabaseName("ix_books_hardcover_id");

                    b.HasIndex("OpenLibraryWorkKey")
                        .IsUnique()
                        .HasDatabaseName("ix_books_open_library_work_key");

                    b.ToTable("books", null, t =>
                        {
                            t.HasCheckConstraint("ck_books_description_source", "description_source in ('hardcover', 'open_library', 'google_books')");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.BookAuthor", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("BookId", "AuthorId", "Role")
                        .HasName("pk_book_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_book_authors_author_id");

                    b.ToTable("book_authors", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.BookGenre", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasColumnName("genre_id");

                    b.HasKey("BookId", "GenreId")
                        .HasName("pk_book_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_book_genres_genre_id");

                    b.ToTable("book_genres", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.BookSeries", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<decimal?>("Position")
                        .HasColumnType("numeric")
                        .HasColumnName("position");

                    b.HasKey("BookId", "SeriesId")
                        .HasName("pk_book_series");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_book_series_series_id");

                    b.ToTable("book_series", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.Edition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AudioSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("audio_seconds");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<long?>("HardcoverEditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("hardcover_edition_id");

                    b.Property<string>("Isbn10")
                        .HasColumnType("text")
                        .HasColumnName("isbn10");

                    b.Property<string>("Isbn13")
                        .HasColumnType("text")
                        .HasColumnName("isbn13");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("OpenLibraryEditionKey")
                        .HasColumnType("text")
                        .HasColumnName("open_library_edition_key");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_editions_book_id");

                    b.HasIndex("HardcoverEditionId")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_hardcover_edition_id");

                    b.HasIndex("Isbn10")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_isbn10");

                    b.HasIndex("Isbn13")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_isbn13");

                    b.HasIndex("OpenLibraryEditionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_open_library_edition_key");

                    b.ToTable("editions", null, t =>
                        {
                            t.HasCheckConstraint("ck_editions_audio_seconds", "audio_seconds > 0");

                            t.HasCheckConstraint("ck_editions_format", "format in ('print', 'ebook', 'audio')");

                            t.HasCheckConstraint("ck_editions_page_count", "page_count > 0");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.ImportItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AddedOn")
                        .HasColumnType("date")
                        .HasColumnName("added_on");

                    b.Property<string>("Asin")
                        .HasColumnType("text")
                        .HasColumnName("asin");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<bool>("CreatedEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("created_entry");

                    b.Property<string>("GoodreadsId")
                        .HasColumnType("text")
                        .HasColumnName("goodreads_id");

                    b.Property<int?>("HardcoverBookId")
                        .HasColumnType("integer")
                        .HasColumnName("hardcover_book_id");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_id");

                    b.Property<string>("Isbn10")
                        .HasColumnType("text")
                        .HasColumnName("isbn10");

                    b.Property<string>("Isbn13")
                        .HasColumnType("text")
                        .HasColumnName("isbn13");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("rating");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<bool>("Written")
                        .HasColumnType("boolean")
                        .HasColumnName("written");

                    b.HasKey("Id")
                        .HasName("pk_import_items");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_import_items_book_id");

                    b.HasIndex("ImportId", "Row")
                        .IsUnique()
                        .HasDatabaseName("ix_import_items_import_id_row");

                    b.ToTable("import_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_import_items_match", "match in ('pending', 'needs_search', 'exact', 'by_title', 'chosen', 'not_found', 'dismissed')");

                            t.HasCheckConstraint("ck_import_items_rating", "rating between 0.5 and 5 and mod(rating * 2, 1) = 0");

                            t.HasCheckConstraint("ck_import_items_status", "status in ('want_to_read', 'reading', 'paused', 'read', 'did_not_finish')");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.LibraryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long?>("EditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("edition_id");

                    b.Property<decimal?>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<string>("ProgressUnit")
                        .HasColumnType("text")
                        .HasColumnName("progress_unit");

                    b.Property<decimal?>("ProgressValue")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_value");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_library_entries");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_library_entries_book_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_library_entries_edition_id");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasDatabaseName("ix_library_entries_user_id_book_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_library_entries_user_id_status");

                    b.ToTable("library_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_library_entries_progress_pair", "(progress_unit is null) = (progress_value is null)");

                            t.HasCheckConstraint("ck_library_entries_progress_percent", "progress_percent between 0 and 100");

                            t.HasCheckConstraint("ck_library_entries_progress_unit", "progress_unit in ('page', 'percent', 'seconds')");

                            t.HasCheckConstraint("ck_library_entries_progress_value", "progress_value >= 0");

                            t.HasCheckConstraint("ck_library_entries_rating", "rating between 0.5 and 5 and mod(rating * 2, 1) = 0");

                            t.HasCheckConstraint("ck_library_entries_status", "status in ('want_to_read', 'reading', 'paused', 'read', 'did_not_finish')");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.LibraryImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("integer")
                        .HasColumnName("batch_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Failures")
                        .HasColumnType("integer")
                        .HasColumnName("failures");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<bool>("OverwriteExisting")
                        .HasColumnType("boolean")
                        .HasColumnName("overwrite_existing");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_library_imports");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_library_imports_user_id_created_at");

                    b.ToTable("library_imports", null, t =>
                        {
                            t.HasCheckConstraint("ck_library_imports_source", "source in ('goodreads', 'story_graph')");

                            t.HasCheckConstraint("ck_library_imports_state", "state in ('matching', 'waiting', 'done', 'failed')");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_profiles_username", "username ~ '^[A-Za-z0-9_-]{3,20}$'");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.Read", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("FinishedDateUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("finished_date_unknown");

                    b.Property<DateOnly?>("FinishedOn")
                        .HasColumnType("date")
                        .HasColumnName("finished_on");

                    b.Property<long>("LibraryEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("library_entry_id");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.HasKey("Id")
                        .HasName("pk_reads");

                    b.HasIndex("LibraryEntryId")
                        .HasDatabaseName("ix_reads_library_entry_id");

                    b.ToTable("reads", null, t =>
                        {
                            t.HasCheckConstraint("ck_reads_dates", "finished_on >= started_on");

                            t.HasCheckConstraint("ck_reads_finished_date_unknown", "not (finished_date_unknown and finished_on is not null)");
                        });
                });

            modelBuilder.Entity("Carrel.Api.Data.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("HardcoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("hardcover_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("HardcoverId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_hardcover_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Carrel.Api.Data.BookAuthor", b =>
                {
                    b.HasOne("Carrel.Api.Data.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_authors_author_id");

                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_books_book_id");

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Carrel.Api.Data.BookGenre", b =>
                {
                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_books_book_id");

                    b.HasOne("Carrel.Api.Data.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_genres_genre_id");

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Carrel.Api.Data.BookSeries", b =>
                {
                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany("Series")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_series_books_book_id");

                    b.HasOne("Carrel.Api.Data.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_series_series_series_id");

                    b.Navigation("Book");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Carrel.Api.Data.Edition", b =>
                {
                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany("Editions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editions_books_book_id");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Carrel.Api.Data.ImportItem", b =>
                {
                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_import_items_books_book_id");

                    b.HasOne("Carrel.Api.Data.LibraryImport", "Import")
                        .WithMany("Items")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_items_library_imports_import_id");

                    b.OwnsMany("Carrel.Api.Data.ImportedRead", "Reads", b1 =>
                        {
                            b1.Property<long>("ImportItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("FinishedDateUnknown");

                            b1.Property<DateOnly?>("FinishedOn");

                            b1.Property<DateOnly?>("StartedOn");

                            b1.HasKey("ImportItemId", "__synthesizedOrdinal");

                            b1.ToTable("import_items");

                            b1
                                .ToJson("reads")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ImportItemId")
                                .HasConstraintName("fk_import_items_import_items_import_item_id");
                        });

                    b.Navigation("Book");

                    b.Navigation("Import");

                    b.Navigation("Reads");
                });

            modelBuilder.Entity("Carrel.Api.Data.LibraryEntry", b =>
                {
                    b.HasOne("Carrel.Api.Data.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_library_entries_books_book_id");

                    b.HasOne("Carrel.Api.Data.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_library_entries_editions_edition_id");

                    b.Navigation("Book");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Carrel.Api.Data.Read", b =>
                {
                    b.HasOne("Carrel.Api.Data.LibraryEntry", "LibraryEntry")
                        .WithMany("Reads")
                        .HasForeignKey("LibraryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reads_library_entries_library_entry_id");

                    b.Navigation("LibraryEntry");
                });

            modelBuilder.Entity("Carrel.Api.Data.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Carrel.Api.Data.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Editions");

                    b.Navigation("Genres");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Carrel.Api.Data.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Carrel.Api.Data.LibraryEntry", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("Carrel.Api.Data.LibraryImport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Carrel.Api.Data.Series", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
